### ISSUE TITLE
Support mapping against multiple genomes

### ISSUE THREAD

**Issue by marcelm** [elsasserlab/minute#26]
The reference is currently fixed for all samples. It would be nice to be able to specify different references for each sample, and also to map one sample against multiple references.

In the configuration, it could look like this:
```
genome:
 - name: mm9
   path: references/mm9.fasta
 - name: grch38
   path: references/human_genome_GRCh38.fasta
```
The given "name" could then be used within the configuration table(s) to refer to the correct genome, and it would also be included in various file names.

Whether the genome to map against should be specified in `libraries.tsv` or `groups.tsv` remains to be determined. Currently, I think it should be `groups.tsv`.

To keep it simple for the typical case in which only a single genome reference is used, the configuration could possibly be simplified this way:
```
genome: references/human_genome_GRCh38.fasta
```
(Distinguishing between these can be done programmatically by checking whether the value for the `'genome'` key is of type list or int.)
